### PR TITLE
Updated Spotify Web Api. Added ability to randomize library albums.

### PR DESCRIPTION
**Pull request by veremenko-y**
It takes time to load all albums and tracks, so I added a progress bar... Sorry for messy callback hell, but I'm not sure how to make it any better really.
I have 161 albums, and it takes few minutes to get all tracks, but it works fine.

### CODE REVIEW

**Comment by TomerAberbach** [comment]
Thanks for the contribution! I'm currently on vacation, but I'll review the PR once I'm back and have some time to spare

**Comment by veremenko-y** [comment]
No problem and no rush. I kinda tried to follow the code style that's there, but I haven't done much JavaScript in a while. So if you have any feedback, let me know and I'll fix it up.

**Review by TomerAberbach — APPROVED** [review]
Looks good! Really like the way the loading looks :smile: 

Just had to fix the playlist track playing (it got broken because in the updated Spotify version they removed the owner parameter).

And no worries about the callback hell. To be honest, I didn't know much about advanced async concepts like promises and async iterables when I first wrote this code. I might refactor it in the future so that it's clearer, but for now I think this is totally fine!

**Comment by TomerAberbach** [comment]
Just deployed this! :rocket:

**Comment by TomerAberbach** [comment]
> I also made another "feature" in my local version, to populate a playlist with all the songs from the library, so I can shuffle then locally. Do you want me to make a PR or it's not really in line with what this app is?

I'm not sure I understand what you mean by "to populate a playlist with all the songs from the library, so I can shuffle then locally." Could you clarify?

**Comment by veremenko-y** [comment]
> I'm not sure I understand what you mean by "to populate a playlist with all the songs from the library, so I can shuffle then locally." Could you clarify?

Sorry, I was not really clear then I forgot to reply lol. It's just a button to that populates a playlist with all the album songs from the library. Because unlike liked songs (sorry), you can't shuffle albums in the client, I find it useful when in car etc.

If you want it, I can push that too, otherwise, I'm running it on my side for myself.

P.S. Interface doesn't look nice anymore, but I'm not good with UI

image

**Comment by TomerAberbach** [comment]
Ah, got it! I would agree that the feature isn't really in line with what this web application is for: shuffling songs with uniform randomness. Glad you were able to get it to work for you on the side though. Enjoy!

**Pull request merged**
